"""
fit_forge_weights.py
====================
Fits the 5 exponent weights of the Forge scoring formula from labeled
training data generated by generate_training_labels.py.

The multiplicative formula in log space:
    log(SCORE) = w_d * log(DOMAIN)
               + w_w * log(WILL)
               + w_a * log(AVAIL)
               + w_p * log(PROX)
               + w_f * log(FRESH)

This is exactly logistic regression on log-transformed features.
The learned coefficients ARE the exponent weights, with no approximation.

Requirements:
    pip install scikit-learn numpy

Usage:
    python fit_forge_weights.py                       # uses default path
    python fit_forge_weights.py --data path/to/csv   # custom path
"""

import argparse
import csv
import json
import math
import os
import sys

_HERE   = os.path.dirname(os.path.abspath(__file__))
DEFAULT_DATA = os.path.join(_HERE, "..", "data", "training_labels.csv")
DEFAULT_OUT  = os.path.join(_HERE, "..", "data", "fitted_weights.json")

FACTOR_NAMES    = ["domain", "will", "avail", "prox", "fresh"]
CURRENT_WEIGHTS = {"domain": 2.0, "will": 1.0, "avail": 0.5, "prox": 1.0, "fresh": 0.5}

EPS = 1e-6   # avoid log(0)


def read_csv(path: str) -> list:
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def build_features(rows: list):
    """
    Log-transform the 5 factor scores to convert the multiplicative formula
    into a linear problem. Rows where domain == 0 are hard rejects by
    definition and are excluded from weight learning.
    """
    X, y, skipped = [], [], 0
    for row in rows:
        d = float(row["domain_score"])
        w = float(row["will_score"])
        a = float(row["avail_score"])
        p = float(row["prox_score"])
        f = float(row["fresh_score"])

        # Zero-domain rows are hard rejects -- they carry no signal for weight fitting
        if d < EPS:
            skipped += 1
            continue

        X.append([
            math.log(d + EPS),
            math.log(w + EPS),
            math.log(a + EPS),
            math.log(p + EPS),
            math.log(f + EPS),
        ])
        y.append(int(row["label"]))

    return X, y, skipped


def fit(data_path: str, out_path: str) -> dict:
    try:
        import numpy as np
        from sklearn.linear_model import LogisticRegression
        from sklearn.model_selection import cross_val_score, StratifiedKFold
        from sklearn.calibration import calibration_curve
    except ImportError:
        print("ERROR: scikit-learn not installed.  Run:  pip install scikit-learn numpy")
        sys.exit(1)

    print(f"Loading training data from {os.path.relpath(data_path)} ...")
    rows = read_csv(data_path)
    print(f"  {len(rows):,} rows loaded.")

    X_raw, y_raw, skipped = build_features(rows)
    print(f"  Excluded {skipped:,} zero-domain rows (hard rejects, no weight signal).")
    print(f"  Training on {len(X_raw):,} samples.")

    X = np.array(X_raw, dtype=float)
    y = np.array(y_raw, dtype=int)

    pos = y.sum()
    print(f"  Class balance: {pos:,} positive ({pos/len(y):.1%}), {len(y)-pos:,} negative")
    print()

    # Logistic regression without intercept: the formula has no bias term.
    # C controls regularization strength; higher C = less regularization.
    clf = LogisticRegression(
        fit_intercept=False,
        C=2.0,
        max_iter=2000,
        solver="lbfgs",
        random_state=42,
    )
    clf.fit(X, y)

    # Cross-validated performance
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    roc_scores = cross_val_score(clf, X, y, cv=cv, scoring="roc_auc")
    acc_scores  = cross_val_score(clf, X, y, cv=cv, scoring="accuracy")
    print(f"5-fold cross-validation:")
    print(f"  ROC-AUC : {roc_scores.mean():.4f}  (+/- {roc_scores.std():.4f})")
    print(f"  Accuracy: {acc_scores.mean():.4f}  (+/- {acc_scores.std():.4f})")
    print()

    raw_coefs = clf.coef_[0]

    # Clip any negative coefficients to a small positive floor.
    # A negative exponent would invert the factor (higher domain = lower score)
    # which is nonsensical for our domain.
    weights = {}
    for name, coef in zip(FACTOR_NAMES, raw_coefs):
        weights[name] = max(0.10, round(float(coef), 4))

    print("Fitted exponent weights vs. current hand-tuned weights:")
    print("-" * 55)
    print(f"  {'Factor':<12} {'Fitted':>10} {'Current':>10}  {'Change':>10}")
    print("-" * 55)
    for name in FACTOR_NAMES:
        fitted  = weights[name]
        current = CURRENT_WEIGHTS[name]
        delta   = fitted - current
        flag    = "  *" if abs(delta) > 0.15 else ""
        print(f"  {name:<12} {fitted:>10.4f} {current:>10.1f}  {delta:>+10.4f}{flag}")
    print("-" * 55)
    print("  (* = differs from current by more than 0.15)")
    print()

    # Save
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    payload = {
        "weights":     weights,
        "meta": {
            "roc_auc_mean": round(float(roc_scores.mean()), 4),
            "roc_auc_std":  round(float(roc_scores.std()),  4),
            "accuracy_mean": round(float(acc_scores.mean()), 4),
            "n_train":      len(X_raw),
            "n_skipped":    skipped,
        }
    }
    with open(out_path, "w") as f:
        json.dump(payload, f, indent=2)
    print(f"Fitted weights saved to {os.path.relpath(out_path)}")

    return weights


def apply_weights_to_forge(weights: dict) -> None:
    """
    Print the FACTOR_WEIGHTS dict update to paste into forge.py.
    """
    print()
    print("To apply these weights, update FACTOR_WEIGHTS in backend/forge.py:")
    print()
    print("FACTOR_WEIGHTS = {")
    for name in FACTOR_NAMES:
        print(f'    "{name}": {weights[name]:.4f},')
    print("}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Fit Forge exponent weights from labeled data.")
    parser.add_argument("--data", default=DEFAULT_DATA, help="Path to training_labels.csv")
    parser.add_argument("--out",  default=DEFAULT_OUT,  help="Path to write fitted_weights.json")
    args = parser.parse_args()

    if not os.path.exists(args.data):
        print(f"Training data not found at {args.data}")
        print("Run:  python generate_training_labels.py")
        sys.exit(1)

    weights = fit(args.data, args.out)
    apply_weights_to_forge(weights)
